"""create shares table

Revision ID: 13c83f773b97
Revises: 15e24347f56a
Create Date: 2026-06-02 20:38:59.599958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13c83f773b97'
down_revision: Union[str, Sequence[str], None] = '15e24347f56a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shares',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resource_type', sa.Enum('file', 'folder', name='resourcetype'), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('shared_with_id', sa.UUID(), nullable=False),
    sa.Column('permission', sa.Enum('viewer', 'editor', name='permissionlevel'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shared_with_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shares')
    # ### end Alembic commands ###
