"""add embedding column to files

Revision ID: 1e49a1e3a044
Revises: 13c83f773b97
Create Date: 2026-06-05 13:10:10.095265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '1e49a1e3a044'
down_revision: Union[str, Sequence[str], None] = '13c83f773b97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    op.add_column('files', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'embedding')
    # ### end Alembic commands ###
